main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    #NAV PATHS
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    #USER PATHS
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    #CARD PATHS
    path('cards/', views.card_index, name='index'),
    #DECK PATHS
    path('decks/', views.deck_index, name='index'),
    path('decks/decks/<int:deck_id>/', views.deck_detail, name='detail'),
    path('decks/create/', views.DeckCreate.as_view(), name='decks_create'),
    path('decks/<int:pk>/update/', views.DeckUpdate.as_view(), name='decks_update'),
    path('decks/<int:pk>/delete/', views.DeckDelete.as_view(), name='decks_delete'),
    #CARDINDECK PATHS
    path('decks/<int:deck_id>/cardsindeck/<int:card_id>/', views.add_cardindeck, name='cardsindeck_create'),
    #path('decks/<int:pk>/update_cardsindeck/', views.CardsInDeckUpdate.as_view(), name='cardindeck_update'),
    #path('decks/<int:pk>/delete_cardsindeck/', views.CardsInDeckDelete.as_view(), name='cardindeck_delete'),

    #DECK TO TEXT PATH
    path('decks/<int:deck_id>/decktotext/', views.deck_text, name='deck_text'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

GAMES = (
    (1, "Unlisted"),
    (2, "Magic the Gathering"),
    (3, "Pokemon"),
    (4, "Yu-Gi-Oh"),
)

class Deck(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.TextField(
        default="No Description"
    )
    game = models.IntegerField(
        choices=GAMES,
        default=GAMES[0][0]
    )

    def __str__(self):
        return self.name
    
class Card(models.Model):
    name = models.CharField(max_length=75)
    game = models.IntegerField(
        choices=GAMES,
        default=GAMES[0][0]
    )
    rarity = models.CharField(max_length=15)
    cardType = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    frontImageURL = models.CharField(max_length=500)
    backImageURL = models.CharField(max_length=500)
    

    def __str__(self):
        return f"Game: {self.game}, Card: {self.name}"
    
class CardInDeck(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(
        default = 1,
    )

    def __str__(self):
        return f"Name: {self.card.name} , Quantity: {self.quantity}"

main_app/forms.py
from django.forms import ModelForm
from .models import CardInDeck

class CardInDeckForm(ModelForm):
  class Meta:
    model = CardInDeck
    fields = []

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from .forms import CardInDeckForm
from django.http import HttpResponse


# Add the following import
from django.http import HttpResponse

#Import Models from .models
from .models import Deck
from .models import Card
from .models import CardInDeck


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def card_index(request):
   cards = Card.objects.all()
   return render(request, 'cards/index.html', {'cards': cards})

def deck_index(request):
   decks = Deck.objects.all()
   return render(request, 'decks/index.html', {'decks': decks})

def deck_detail(request, deck_id):
   deck = Deck.objects.get(id=deck_id)
   cardsindeck_form = CardInDeckForm
   cards = Card.objects.filter(game=deck.game)
   cardsindeck = CardInDeck.objects.all()
   cards_not_in_deck = Card.objects.exclude(id__in = cardsindeck.all().values_list('id')) #Excludes all cards in any deck. I want all cards in THIS deck to be excluded.
   
   
   return render(request, 'decks/detail.html', {
      'deck': deck,
      'cards': cards,
      'cardsindeck': cardsindeck,
      'cardsindeck_form': cardsindeck_form,
   })

#Login Required Functionality

#Deck Functionality
class DeckCreate(LoginRequiredMixin, CreateView):
    model = Deck
    fields = ['name', 'description', 'game']
    success_url = '/decks/'

    def form_valid(self, form):
      form.instance.user = self.request.user
      return super().form_valid(form)
   
class DeckUpdate(LoginRequiredMixin, UpdateView):
    model = Deck
    fields = ['name', 'description', 'game']
    success_url = '/decks/'

class DeckDelete(LoginRequiredMixin, DeleteView):
    model = Deck
    success_url = '/decks/'

#CardsInDeck Functionality

@login_required
def add_cardindeck(request, deck_id, card_id):
    deck = Deck.objects.filter(id=deck_id).first()
    card = Card.objects.get(id=card_id)
    form = CardInDeckForm(request.POST)
    print(form)
    if form.is_valid():
        new_cardindeck = form.save(commit=False)
        new_cardindeck.deck = deck
        new_cardindeck.card = card
        new_cardindeck.quantity = 1
        new_cardindeck.save()
    return redirect('detail', deck_id=deck_id)


class CardsInDeckUpdate(LoginRequiredMixin, UpdateView):
    model = CardInDeck
    fields = ['quantity']
    success_url = '/decks/'

    def form_valid(self, form):
        edit_cardsindeck = form.save(commit=False)
        print(edit_cardsindeck.user)
        if self.request.user.id != edit_cardsindeck.user.id:
            return redirect('detail', deck_id=edit_cardsindeck.deck.id)
        return super().form_valid(form)
    
    def get_success_url(self):
        obj = self.get_object()
        return redirect('index')


class CardsInDeckDelete(LoginRequiredMixin, DeleteView):
    model = CardInDeck
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        if self.object.user.id == request.user.id:
            self.object.delete()
        return redirect('detail', deck_id=self.object.deck.id)

    def get_success_url(self):
        obj = self.get_object()
        print(obj)
        return reverse('detail', kwargs={'deck_id': obj.deck.id})
    
#GENERATE TEXT FILE
def deck_text(request, deck_id):
    cards = CardInDeck.objects.all()
    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename=deck.txt'

    lines = []
    for card in cards:
        if card.deck.id == deck_id:
          lines.append(f'{card.quantity} {card.card.name}\n')

    response.writelines(lines)
    return response

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>Universal Deck Builder</h1>
<hr />
<h5 class="about_h">Development</h5>
<p class="about">Developed over the course of the Spring of 2024 by Zach Oandasan, the project was initially concieved after a new card game was brought to the attention of the creator. He went to search for any methods of trying the game. Unfortunately, there was no dedicated service to the game avaliable. Thus, a new idea was created.</p>
<h5 class="about_h">Functionality</h5>
<p class="about">The Universal Deck Builder is constantly adding new cards to their database. Users will be allowed to build decks using these cards.</p>
<p class="about">Once a user is satisfied by their deck, the user can export their deck to either a printable image to play in paper, or as a .JSON file to be exported to a virtual tabletop.</p>


{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Universal Deck Builder</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul class="right">
          {% if user.is_authenticated %}
          <li><a href="/">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/decks">My Decks</a></li>
          <li><a href="/cards">Card List</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2024 Universal Deck Builder &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/cards/index.html
{% extends 'base.html' %}
{% block content %}

{% if request.user %}
    <h5 style="text-align: center; ">Cards:</h5>
    <hr>
    <table class="highlight">
        <thead>
        <tr>
            <th>Card Name:</th>
            <th>Game:</th>
            <th>Card Type:</th>
            <th>Description:</th>
            <th>Rarity:</th>
            <th>Image:</th>
        </tr>
        </thead>
        <tbody>
            {% for card in cards %}
            <tr>
                <td>{{ card.name }}</td>

                {% if card.game == 4 %}
                <td>Yu-Gi-oh</td>
                {% elif card.game == 3 %}
                <td>Pokemon</td>
                {% elif card.game == 2 %}
                <td>Magic The Gathering</td>
                {% else %}
                <td>Unlisted</td>
                {% endif%}

                <td>{{ card.cardType }}</td>
                <td>{{ card.description }}</td>
                <td>{{ card.rarity }}</td>
                <td><button class="btn"><a href="{{card.frontImageURL}}">view</a></button></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
{% endif %}

{% endblock %}

main_app/templates/decks/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Deck List</h1>

<div class="card-panel">
  <div class="card-content">
    <span class="card-title">{{ deck.name }}</span>

    {% if deck.game == 4 %}
        <p>Game: Yu-Gi-oh</p>
        {% elif deck.game == 3 %}
        <p>Game: Pokemon</p>
        {% elif deck.game == 2 %}
        <p>Game: Magic The Gathering</p>
        {% else %}
        <p>Game: Unlisted</p>
    {% endif%}
    <p>Description: {{ deck.description }}</p>
    <div class="card-action" style="text-align: center;">
      <button><a href="{% url 'decks_update' deck.id %}">Edit Deck</a></button>
      <button><a href="{% url 'deck_text' deck.id %}">Download Deck as Text</a></button>
      <button><a href="{% url 'decks_delete' deck.id %}">Delete Deck</a></button>
    </div>
  </div>
</div>


  <h5 style="text-align: center; ">Cards in Deck:</h5>
  
    <hr>
    <table class="highlight">
        <thead>
        <tr>
            <th>Card Name:</th>
            <th>Card Type:</th>
            <th>Description:</th>
            <th>Quantity</th>
            <th>View Image/Delete:</th>
        </tr>
        </thead>
        
        <tbody>
            {% for cardindeck in cardsindeck %}
              {% if deck.id == cardindeck.deck.id %}
                <tr>
                  <td>{{ cardindeck.card.name }}</td>
                  <td>{{ cardindeck.card.cardType }}</td>
                  <td>{{ cardindeck.card.description }}</td>
                  <td>{{ cardindeck.quantity }}</td>
                  <td>
                    <button class="btn"><a href="{{cardindeck.card.frontImageURL}}">view</a></button>
                    <button class="btn"><a href="">delete</a></button>
                  </td>
                </tr>
              {% endif %}
            {% endfor %}
        </tbody>
    </table>

    <h5 style="text-align: center; ">Cards:</h5>
    <hr>
    <table class="highlight">
        <thead>
        <tr>
            <th>Card Name:</th>
            <th>Card Type:</th>
            <th>Description:</th>
            <th>Rarity:</th>
            <th>Image:</th>
        </tr>
        </thead>
        <tbody>
            {% for card in cards %}
            {% if card.game == deck.game %}
            {% if card.id != cardindeck.card.id %}
            <tr>
                <td>{{ card.name }}</td>


                <td>{{ card.cardType }}</td>
                <td>{{ card.description }}</td>
                <td>{{ card.rarity }}</td>
                <td>
                  <button class="btn"><a href="{{card.frontImageURL}}">view</a></button>
                  <form action="{% url 'cardsindeck_create' deck.id card.id %}" method="POST">
                    {% csrf_token %}
                    {{ cardindeck_form.as_p }}
                    <input type="submit" class="btn" value="Add Card">
                  </form>
                </td>
            </tr>
            
            {% endif %}
            {% endif %}
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

main_app/templates/decks/index.html
{% extends 'base.html' %}
{% block content %}

{% if request.user %}
    <h5 style="text-align: center; ">Decks by {{ user.username }}:</h5>
    <hr>
    <h5 style="text-align: center; "><button class="btn"><a href="{% url 'decks_create' %}">New Deck</a></button></h5>
    <table class="highlight">
        <thead>
        <tr>
            <th>Deck Name:</th>
            <th>Game:</th>
            <th>Description:</th>
            <th>View Deck:</th>
        </tr>
        </thead>
        <tbody>
            {% for deck in user.deck_set.all %}
            <tr>
                <td>{{ deck.name }}</td>

                {% if deck.game == 4 %}
                <td>Yu-Gi-oh</td>
                {% elif deck.game == 3 %}
                <td>Pokemon</td>
                {% elif deck.game == 2 %}
                <td>Magic The Gathering</td>
                {% else %}
                <td>Unlisted</td>
                {% endif%}

                <td>{{ deck.description }}</td>
                
                <td>
                    <button class="btn"><a href="decks/{{ deck.id }}">view</a></button> 
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    
    
{% endif %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1 style="margin-bottom: 25px;">Welcome!</h1>
<div  style="margin-bottom: 10rem;">
    <p style="font-size:x-large; text-align: center;">Welcome to The Universal Deck Builder, the one stop you need for card game proxy needs.</p>
    <br>
    <p style="font-size:x-large; text-align: center;">Please <a href="/accounts/login">Login</a> to get started!</p>
</div>

{% endblock %}

main_app/templates/main_app/cardindeck_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Deck</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn">
    <a href="{% url 'detail' deck.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/cardindeck_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Add Deck</h1>
{% else %}
<h1>Edit Deck</h1>
{% endif %}
  <div class="card-panel">
    <div class="card-content">
    <form action="" method="post" style="margin: 5%">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <div class="post-btn" style="display: flex;
        justify-content: center;
        margin-top: inherit;">
        <input type="submit" value="Post" class="btn" style="background-color: #DA2D7C; font-size: 2rem;">
      </div>
    </form>
    </div>
  </div>

{% endblock %}

main_app/templates/main_app/deck_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Deck</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn">
    <a href="{% url 'detail' deck.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/deck_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Add Deck</h1>
{% else %}
<h1>Edit Deck</h1>
{% endif %}
  <div class="card-panel">
    <div class="card-content">
    <form action="" method="post" style="margin: 5%">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <div class="post-btn" style="display: flex;
        justify-content: center;
        margin-top: inherit;">
        <input type="submit" value="Post" class="btn" style="background-color: #DA2D7C; font-size: 2rem;">
      </div>
    </form>
    </div>
  </div>

{% endblock %}